---
title: "R Heatmap BY4741 +- Laccase"
author: "Ryan Wong"
date: "2023-09-22"
output: html_document
---

## Load packages

```{r}

library(ggplot2)
library(tidyverse)

```

## Set save parameters

```{r}

save_pdf <- T

save_svg <- T

```

## Read in data

```{r}

setwd("D:/+_-_Laccase/BY4741 TtL") #Change to the directory which contains the data

dat <- read.delim("BY4741 Time-course.txt", header = TRUE, sep = "\t") #Sheet 1 of Supplemental File 2

```

## Run linear modeling

```{r}
out <- c()
vals <- c()
for (i in colnames(dat[,3:length(dat)])) {
  dat.fil <- dplyr::select(dat, i)
  for (j in colnames(dat[,3:length(dat)])) {
  dat.fil2 <- dplyr::select(dat, j)
  rs <- lm(dat.fil[,1]~dat.fil2[,1])
  r <- cbind(i,j,summary(rs)$r.squared)
  out <- rbind(out, r)
  }
  vals<- rbind(vals, out)
}
```
 
## Write r values and sample names to tables

```{r}
rsq <- as.data.frame(vals)
rsq$r2 <- as.numeric(rsq$V3)
rsq$r <- sqrt(rsq$r2)
nam.i <-str_remove(rsq$i, regex("\\w{1}.\\d+..Ryan_"))
nam.j <-str_remove(rsq$j, regex("\\w{1}.\\d+..Ryan_"))
rsq$nam.i <-   str_sub(nam.i, 1,16)
rsq$nam.j <-  str_sub(nam.j, 1,16)
write.table(rsq, "r_lm_heatmap.txt", row.names = FALSE, sep = "\t")
```

## Plot heatmap and save image in current directory

```{r}

HM <- ggplot(rsq, aes(x= fct_inorder(nam.i), y= fct_inorder(nam.j), fill = r))+
  geom_tile()+
  scale_fill_gradient(low = "white", high = "green4", limits = c(0.75, 1)) +
  scale_x_discrete(guide = guide_axis(angle = 90))+
  theme(text = element_text(size = 6))

HM

if (save_pdf == T){

  setwd("D:/+_-_Laccase/BY4741 TtL")
  
  ggsave("r_green4_sq_075-1.pdf", plot = HM, device = "pdf", width = 11.8, height = 10, units = "cm", dpi = 1000)
  
}

if(save_svg == T){

  setwd("D:/+_-_Laccase/BY4741 TtL")
  
  ggsave("r_green4_sq_075-1.svg", plot = HM, device = "svg", width = 11.8, height = 10, units = "cm", dpi = 1000)
  
}

```